base_url = "/"
title = "My Blog"
description = "A demonstration of Markdown elements"
compile_sass = false
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
author = "John Doe"

# Theme settings
# default_theme: "light", "dark", or "auto" (uses system preference)
default_theme = "light"
# Enable theme selector in UI (true/false)
enable_theme_selector = true