base_url = "/"
title = "My Blog"
description = "A demonstration of Markdown elements"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "css"
definition_list = true
gfm = true
subsupscript = true
github_alerts = true

[languages.ua.translations]
summary = "Мій блог"

[translations]
summary = "My blog"

[extra]
author = "John Doe"

# Theme settings: auto, light, dark, default = auto
color_scheme = "auto"

# Flavor settings
# default_flavor: Sets the default flavor to use
#   - "happy-headers": Colorful headers with gradient-2
#   - "happy": Colorful headers and bold text with gradient-2
#   - "deep-headers": Colorful headers with gradient-1
#   - "deep": Colorful headers and bold text with gradient-1
#   - "monochrome": Plain black text for headers and bold text
flavor = "deep-headers"
