base_url = "/"
title = "My Blog"
description = "A demonstration of Markdown elements"
compile_sass = false
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
author = "John Doe" 