name = "pechersk"
description = "Modern blog scheme with sidenotes"
min_version = "0.0.1"
license = "MIT"
homepage = "https://github.com/ctrlok/pechersk"
demo = "https://dvps.blog"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

[author]
name = "Seva Poliakov"
homepage = "seva.rocks"
